- name: mysql IP address
  shell: docker inspect mysql | grep IPAddres | awk -F'"' '{print $4}'
  register: ip

- name: create mysql db
  mysql_db: login_host={{ip.stdout}} login_user=root login_password= name=gitlabhq_production encoding=utf8 collation=utf8_unicode_ci

- name: create gitlab user
  mysql_user: login_host={{ip.stdout}} login_user=root login_password=  name=gitlab host=172.17.%.% password=password priv=gitlabhq_production.*:ALL,GRANT

- name: setup gitlab container
  docker: image=sameersbn/gitlab:latest name=gitlab stdin_open=true tty=true links=mysql:mysql env="DB_USER=gitlab,DB_PASS=password,DB_NAME=gitlabhq_production" volumes=/opt/gitlab/data:/home/git/data command="app:rake gitlab:setup"

