- name: mysql IP address
  shell: sudo docker inspect mysql | grep IPAddres | awk -F'"' '{print $4}'
  register: ip

- name: create mysql db
  mysql_db: login_host={{ip.stdout}} login_user=root login_password= name=redmin_production encoding=utf8 collation=utf8_unicode_ci


- name: create redmine user
  mysql_user: login_host={{ip.stdout}} login_user=root login_password=  name=redmine host=172.17.%.% password=password priv=redmine_production.*:ALL,GRANT

- name: create redmine directory
  file: path=/opt/redmine/files state=directory

- name: redmine-init
  script: redmine-init.sh creates=/opt/shell/redmine-init-done.txt

- name: redmine-init-done
  file: path=/opt/shell/redmine-init-done.txt state=touch

- name: redmine-start
  script: redmine-start.sh







