- name: base module install
  apt: name={{ item }} update_cache=yes
  with_items:
    - git
    - software-properties-common
    - python
    - python-pip
    - python-configparser
    - python-mysqldb

- name: docker-py install 
  pip: name=docker-py



